### ISSUE TITLE
Invite Friend&Join Friend Feature

### ISSUE THREAD

**Issue by TheYellowArchitect** [phalasz/forgesteamworksexample#1]
(First time I open a issue, sorry for the un-structured format)

This steam example is super helpful because it utilizes steam lobbies, and also connecting via the steam network instead of manually NATPunching.

However, there is another use-case someone might have for implementing Steamworks, which is for Invite/Join via the Steam Overlay.

So, a player opens up his friend list and invites a friend, and if the receiving player accepts, they connect. Idk details as to if it should be made by a lobby which is made under-the-hood and auto-connects the 2, but as long as this invite/accept request works, I really think this steam example covers all the basic and common use-cases

Thanks again for this, there is so much useful and digestible info in this, where before this, most ppl just gave up trying to set up their own "boilerplate" code of steamworks, that doesn't even come close to this

**Comment by phalasz** [comment]
[Latest test clients (v0.1.0)](https://github.com/phalasz/forgesteamworksexample/releases/tag/0.1.0) should allow invites when the player to be invited is already at the menu in game.
The person making the invite should be actually playing.

Inviting steam friends not in game is hard to test as that would require a properly installed steam game instead of using the test app id.

If both steam users are playing a game in different lobbies then invites don't work as the person being invited can accept the invite, but the game will not switch to the other lobby/game.

One future enhancement could be to allow sending invites while on the menu screen and auto start a game host when sending the invite if that is possible.
